name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        std: [23]
        build_type: [Debug]
        warnings_as_errors: [WARNINGS_AS_ERRORS=OFF, WARNINGS_AS_ERRORS=ON]
        sanitizer: ['']

        include:
          - compiler: g++
            std: 23
            build_type: Debug
            sanitizer: -fsanitize=address
            warnings_as_errors: WARNINGS_AS_ERRORS=OFF

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install packages
      # nix caches packages, so this will do the installs.
      run: nix develop

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ci-${{ matrix.compiler }}-${{ matrix.build_type }}-${{ matrix.sanitizer }}

    - name: Configure
      run: nix develop --command
            cmake -S. -B${{ runner.workspace }}/build
            -GNinja
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}
            -DNOCTERN_${{ matrix.warnings_as_errors }}
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_FLAGS_INIT='${{ matrix.sanitizer }}'
            -DCMAKE_EXE_FLAGS_INIT='${{ matrix.sanitizer }}'
            -DCMAKE_STATIC_FLAGS_INIT='${{ matrix.sanitizer }}'
            -DCMAKE_SHARED_FLAGS_INIT='${{ matrix.sanitizer }}'

    - name: Build
      run: nix develop --command
            cmake --build ${{ runner.workspace }}/build --config ${{ matrix.build_type }}

    - name: Run Tests
      run: nix develop --command
            ctest --test-dir ${{ runner.workspace }}/build -C ${{ matrix.build_type }} -VV
            --output-junit ${{ runner.workspace }}/build/test-results.xml
            
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Noctern Tests
        path: ${{ runner.workspace }}/build/test-results.xml
        reporter: java-junit
