name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cxx: [g++, clang++]
        std: [20, 23]
        build_type: [Debug, Release]

    steps:
    - name: Print Configuration
      run: |
        ${{ matrix.cxx }} --version
        echo std=c++${{ matrix.std }}
        cmake --version

    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Configure
      run: nix-shell --run 'cmake -S. -B${{ runner.workspace }}/build
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}
            -DNOCTERN_WARNINGS_AS_ERRORS=ON'

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      run: cmake --build . --config ${{ matrix.build_type }} -j2

    - name: Run Tests
      working-directory: ${{ runner.workspace }}/build
      run: ctest -C ${{ matrix.build_type }} -VV
