name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        std: [23]
        build_type: [Debug]
        warnings_as_errors: [false, true]

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install packages
      # nix caches packages, so this will do the installs.
      run: nix develop

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure
      run: nix develop --command
            cmake -S. -B${{ runner.workspace }}/build
            -GNinja
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_CXX_STANDARD=${{ matrix.std }}
            -DNOCTERN_WARNINGS_AS_ERRORS=${{ matrix.warnings_as_errors }}
            -DCMAKE_C_COMPILER_LAUNCHER=ccache
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: nix develop --command
            cmake --build ${{ runner.workspace }}/build --config ${{ matrix.build_type }}

    - name: Run Tests
      run: nix develop --command
            ctest --test-dir ${{ runner.workspace }}/build -C ${{ matrix.build_type }} -VV
